import { v4 as uuidv4 } from 'uuid';
import type { Card, Deck } from '../types';
import { DEFAULT_DECK_SETTINGS } from '../types';
import { db } from './db';

const DEFAULT_DECK_ID = 'default-deck-001';

const defaultDeck: Deck = {
  id: DEFAULT_DECK_ID,
  name: 'Getting Started',
  description: 'Learn how to use FlashMaster with these sample cards. Feel free to edit or delete this deck!',
  color: '#6366f1',
  icon: '🚀',
  createdAt: Date.now(),
  updatedAt: Date.now(),
  settings: { ...DEFAULT_DECK_SETTINGS },
  tags: ['tutorial', 'getting-started'],
};

const defaultCards: Omit<Card, 'id'>[] = [
  {
    deckId: DEFAULT_DECK_ID,
    front: '## What is Spaced Repetition?\n\n*Think about the most efficient way to memorize...*',
    back: '**Spaced Repetition** is a learning technique where you review information at increasing intervals.\n\nCards you know well are shown less frequently, while difficult cards appear more often.\n\n> "The spacing effect is one of the most robust findings in cognitive psychology." — Cepeda et al.',
    tags: ['concept'],
    noteType: 'basic',
    createdAt: Date.now(),
    updatedAt: Date.now(),
    status: 'new',
    ease: 2.5,
    interval: 0,
    dueDate: Date.now(),
    lapses: 0,
    reps: 0,
    learningStep: 0,
  },
  {
    deckId: DEFAULT_DECK_ID,
    front: '## How do the rating buttons work?\n\n🔴 Again &nbsp; 🟠 Hard &nbsp; 🟢 Good &nbsp; 🔵 Easy',
    back: '| Button | Effect |\n|--------|--------|\n| **Again** 🔴 | Card was forgotten — reset and show soon |\n| **Hard** 🟠 | Partially remembered — shorter interval |\n| **Good** 🟢 | Remembered well — normal interval |\n| **Easy** 🔵 | Very easy — longer interval, bonus XP |\n\nThe intervals automatically adjust based on your performance!',
    tags: ['usage'],
    noteType: 'basic',
    createdAt: Date.now(),
    updatedAt: Date.now(),
    status: 'new',
    ease: 2.5,
    interval: 0,
    dueDate: Date.now(),
    lapses: 0,
    reps: 0,
    learningStep: 0,
  },
  {
    deckId: DEFAULT_DECK_ID,
    front: '## What formats are supported for cards?\n\nHint: FlashMaster supports rich content!',
    back: 'FlashMaster supports:\n\n- **Markdown** — headers, bold, italic, lists, tables\n- **HTML** — any valid HTML content\n- **Images** — paste URLs or upload images\n- **Code blocks** — syntax highlighting\n\n```javascript\nconst greeting = "Hello, FlashMaster!";\nconsole.log(greeting);\n```\n\n> Cards can contain any combination of these formats!',
    tags: ['features'],
    noteType: 'basic',
    createdAt: Date.now(),
    updatedAt: Date.now(),
    status: 'new',
    ease: 2.5,
    interval: 0,
    dueDate: Date.now(),
    lapses: 0,
    reps: 0,
    learningStep: 0,
  },
  {
    deckId: DEFAULT_DECK_ID,
    front: '## What is the XP & Leveling system?\n\n⭐ How does gamification work?',
    back: '### Gamification in FlashMaster\n\n- **XP Points**: Earn XP for every card you study\n  - Easy: 15 XP\n  - Good: 10 XP\n  - Hard: 8 XP\n  - Again: 5 XP\n\n- **Streak Bonus**: Extra XP for consecutive daily study\n- **Levels**: Level up every 100 XP\n- **Achievements**: Unlock badges for milestones\n\nKeep studying to climb the ranks! 🏆',
    tags: ['gamification'],
    noteType: 'basic',
    createdAt: Date.now(),
    updatedAt: Date.now(),
    status: 'new',
    ease: 2.5,
    interval: 0,
    dueDate: Date.now(),
    lapses: 0,
    reps: 0,
    learningStep: 0,
  },
  {
    deckId: DEFAULT_DECK_ID,
    front: '## How to import Anki decks?\n\n📥 Bring your existing flashcards!',
    back: '### Importing from Anki\n\n1. Export your Anki deck as `.apkg` file\n2. Go to **Settings** → **Import / Export**\n3. Click **Import Anki Deck**\n4. Select your `.apkg` file\n\nYour cards, including their review history, will be imported!\n\n*You can also export FlashMaster decks back to Anki format.* 🔄',
    tags: ['import', 'anki'],
    noteType: 'basic',
    createdAt: Date.now(),
    updatedAt: Date.now(),
    status: 'new',
    ease: 2.5,
    interval: 0,
    dueDate: Date.now(),
    lapses: 0,
    reps: 0,
    learningStep: 0,
  },
  {
    deckId: DEFAULT_DECK_ID,
    front: '## How does offline mode work?\n\n📱 Study anywhere, anytime!',
    back: '### Offline-First Design\n\nFlashMaster works **completely offline**:\n\n- All data is stored locally in your browser\n- Install as a **PWA** for native app experience\n- **Sync** your data via:\n  - JSON export/import\n  - iCloud Drive / Google Drive folder sync\n  - Manual backup & restore\n\nYour learning never stops, even without internet! 🌐',
    tags: ['offline', 'sync'],
    noteType: 'basic',
    createdAt: Date.now(),
    updatedAt: Date.now(),
    status: 'new',
    ease: 2.5,
    interval: 0,
    dueDate: Date.now(),
    lapses: 0,
    reps: 0,
    learningStep: 0,
  },
  {
    deckId: DEFAULT_DECK_ID,
    front: '# 🇩🇪 German Vocabulary\n\n**der Hund**',
    back: '# 🐕 the dog\n\n**der Hund** (masculine)\n\n*Plural: die Hunde*\n\nExample:\n> *Der Hund spielt im Park.*\n> The dog plays in the park.',
    tags: ['german', 'vocabulary', 'animals'],
    noteType: 'basic',
    createdAt: Date.now(),
    updatedAt: Date.now(),
    status: 'new',
    ease: 2.5,
    interval: 0,
    dueDate: Date.now(),
    lapses: 0,
    reps: 0,
    learningStep: 0,
  },
  {
    deckId: DEFAULT_DECK_ID,
    front: '# 🇩🇪 German Vocabulary\n\n**die Katze**',
    back: '# 🐈 the cat\n\n**die Katze** (feminine)\n\n*Plural: die Katzen*\n\nExample:\n> *Die Katze schläft auf dem Sofa.*\n> The cat sleeps on the sofa.',
    tags: ['german', 'vocabulary', 'animals'],
    noteType: 'basic',
    createdAt: Date.now(),
    updatedAt: Date.now(),
    status: 'new',
    ease: 2.5,
    interval: 0,
    dueDate: Date.now(),
    lapses: 0,
    reps: 0,
    learningStep: 0,
  },
];

export async function seedDefaultDeck() {
  const existingDeck = await db.decks.get(DEFAULT_DECK_ID);
  if (existingDeck) return; // Already seeded

  await db.decks.put(defaultDeck);
  const cards = defaultCards.map(c => ({ ...c, id: uuidv4() }));
  await db.cards.bulkPut(cards);
}
