import { cleanupOutdatedCaches, precacheAndRoute } from 'workbox-precaching'
import { registerRoute, NavigationRoute } from 'workbox-routing'
import { CacheFirst, NetworkFirst, StaleWhileRevalidate } from 'workbox-strategies'
import { CacheableResponsePlugin } from 'workbox-cacheable-response'
import { ExpirationPlugin } from 'workbox-expiration'
import { clientsClaim } from 'workbox-core'

// Clean up old caches that are no longer needed
cleanupOutdatedCaches()

// Take control immediately
clientsClaim()

// Precache all assets generated by the build process
// self.__WB_MANIFEST is injected by Workbox during the build
precacheAndRoute(self.__WB_MANIFEST)

// ---------------------------------------------------------------------------
// Network First Strategy for Navigation Requests (HTML)
// ---------------------------------------------------------------------------
// This ensures that if the network is available, we try to fetch the latest
// version of the page. If the network fails, we fall back to the cache.
// This is crucial for SPA updates and reliable offline access.
// We use a custom handler to exclude specific paths like API calls or verify cached responses.
// ---------------------------------------------------------------------------
const navigationStrategy = new NetworkFirst({
    cacheName: 'pages',
    plugins: [
        new CacheableResponsePlugin({
            statuses: [0, 200], // Cache opaque responses (0) and successful responses (200)
        }),
    ],
})

const navigationRoute = new NavigationRoute(navigationStrategy, {
    // Exclude non-HTML requests or specific API routes if needed
    // denylist: [/^\/api\//], 
})

registerRoute(navigationRoute)

// ---------------------------------------------------------------------------
// Stale While Revalidate Strategy for CSS, JS, and Workers
// ---------------------------------------------------------------------------
// Serve cached content immediately while updating the cache in the background.
// This ensures fast load times for static assets that might change occasionally.
// ---------------------------------------------------------------------------
registerRoute(
    ({ request }) =>
        request.destination === 'style' ||
        request.destination === 'script' ||
        request.destination === 'worker',
    new StaleWhileRevalidate({
        cacheName: 'static-resources',
        plugins: [
            new CacheableResponsePlugin({
                statuses: [0, 200],
            }),
        ],
    })
)

// ---------------------------------------------------------------------------
// Cache First Strategy for Images
// ---------------------------------------------------------------------------
// Images rarely change, so we serve them from the cache first.
// We limit the cache size and age to prevent it from growing effectively.
// ---------------------------------------------------------------------------
registerRoute(
    ({ request }) => request.destination === 'image',
    new CacheFirst({
        cacheName: 'images',
        plugins: [
            new CacheableResponsePlugin({
                statuses: [0, 200],
            }),
            new ExpirationPlugin({
                maxEntries: 60,
                maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
            }),
        ],
    })
)

// ---------------------------------------------------------------------------
// Cache First Strategy for Fonts (Google Fonts)
// ---------------------------------------------------------------------------
// Cache the underlying font files with a cache-first strategy for 1 year.
// ---------------------------------------------------------------------------
registerRoute(
    /^https:\/\/fonts\.gstatic\.com/,
    new CacheFirst({
        cacheName: 'google-fonts-webfonts',
        plugins: [
            new CacheableResponsePlugin({
                statuses: [0, 200],
            }),
            new ExpirationPlugin({
                maxAgeSeconds: 60 * 60 * 24 * 365,
                maxEntries: 30,
            }),
        ],
    })
)

// Cache the Google Fonts stylesheets with a stale-while-revalidate strategy.
registerRoute(
    /^https:\/\/fonts\.googleapis\.com/,
    new StaleWhileRevalidate({
        cacheName: 'google-fonts-stylesheets',
    })
)

// ---------------------------------------------------------------------------
// Offline Fallback (Optional but recommended)
// ---------------------------------------------------------------------------
// Navigate fallback is handled by precacheAndRoute if configured in workbox-config
// or via the NavigationRoute above.
// If valid index.html is precached, it acts as the offline page for SPA.

self.addEventListener('message', (event) => {
    if (event.data && event.data.type === 'SKIP_WAITING') {
        self.skipWaiting()
    }
})
